Add mod tidy and go generate checks in github workflows

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -10,18 +10,52 @@ permissions:
   contents: read
 
 jobs:
-  golangci:
-    name: lint
+  lint:
+    name: Verify linting
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v5
       - uses: actions/setup-go@v6
         with:
           go-version: stable
+      - name: Run go vet
+        run: go vet ./...
       - name: golangci-lint
         uses: golangci/golangci-lint-action@v8
         with:
           version: v2.5
+
+  mod-tidy:
+    name: Check if go mod tidy is needed
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v5
+      - uses: actions/setup-go@v6
+        with:
+          go-version: stable
+      - run: |
+          go mod tidy
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "go mod tidy failed"
+            git diff
+            exit 1
+          fi
+
+  go-generate:
+    name: Check if generated files are up to date
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v5
+      - uses: actions/setup-go@v6
+        with:
+          go-version: stable
+      - run: |
+          go generate ./...
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "Generated files are out of date. Please run 'go generate ./...' and commit the changes."
+            git diff
+            exit 1
+          fi
 
   test:
     name: Run Go Tests
@@ -31,15 +65,10 @@ jobs:
       - uses: actions/setup-go@v6
         with:
           go-version: stable
-
-      - name: Run tests
-        run: go test ./... -v -coverprofile=profile.cov
+      - run: go test ./... -v -coverprofile=profile.cov
       - uses: shogo82148/actions-goveralls@v1
         with:
           path-to-profile: profile.cov
       - uses: codecov/codecov-action@v5
         with:
           files: profile.cov
-
-      - name: Run go vet
-        run: go vet ./...
